name: getx_pattern_starter_project_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.5
  flutter_native_splash: 1.2.1
  flutter_launcher_icons: 0.9.1
  introduction_screen: ^2.1.0
  firebase_core: 1.4.0
  firebase_auth: 3.0.1
  logger: ^1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/images/splash.png

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true
  remove_alpha_ios: true

